### ISSUE TITLE
Not able to run it on Windows 10

### ISSUE THREAD

**Issue by seme1** [nesk/puphpeteer#35] opened 2019-02-01 20:12 UTC
Getting the following when attempting to run the first simple example in the documentation of taking a screenshot of example.com

```
Notice: Use of undefined constant SOCKET_EAGAIN - assumed 'SOCKET_EAGAIN' in C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\nesk\rialto\src\ProcessSupervisor.php on line 430

Fatal error: Uncaught Socket\Raw\Exception: Socket operation failed: A non-blocking socket operation could not be completed immediately. (SOCKET_EWOULDBLOCK) in C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\clue\socket-raw\src\Exception.php:55 Stack trace: #0 C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\clue\socket-raw\src\Exception.php(24): Socket\Raw\Exception::createFromCode(10035, 'Socket operatio...') #1 C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\clue\socket-raw\src\Socket.php(247): Socket\Raw\Exception::createFromSocketResource(Resource id #52) #2 C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\nesk\rialto\src\ProcessSupervisor.php(409): Socket\Raw\Socket->read(1024) #3 C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\nesk\rialto\src\ProcessSupervisor.php(382): Nesk\Rialto\ProcessSupervisor->readNextProcessValue(true) #4 C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(83): Nesk\Rialto\ProcessSupervisor->executeInstruction in C:\xampp\htdocs\assets\APIs_vendor\puppeteer\vendor\clue\socket-raw\src\Exception.php on line 55
```

Running on Windows 10 with PHP 7.1
Installed with composer as mentioned in the instructions.

**Comment by nesk** [comment] 2019-03-24 16:29
I've downloaded the Windows 10 virtual machine provided by Microsoft [on their website](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and then installed XAMPP and Node.js. I was able to run all of the README examples without any issue.

I'm closing this issue, but if you still encounter this, provide me a reproducible example (it can be a VMware VM) so I can test myself and I will reopen the issue.

**Closed by nesk** 2019-03-24 16:29 UTC
Labels: bug

**Comment by UMAIR2282** [comment] 2019-05-14 13:02
@seme1 were you able to resolve this issue?

**Comment by ping-xiong** [comment] 2019-05-17 07:00
> @seme1 were you able to resolve this issue?

I got this issue

`"Use of undefined constant SOCKET_EAGAIN - assumed 'SOCKET_EAGAIN' (this will throw an Error in a future version of PHP)"`

![TIM截图20190517145502](https://user-images.githubusercontent.com/14366866/57909124-78582600-78b4-11e9-9b6f-19d01b797fef.jpg)


But I resolved the issue by adding options 

`'args' => ['--no-sandbox', '--disable-setuid-sandbox']`

![})CF`2PFS5$ROO02FCBT_}S](https://user-images.githubusercontent.com/14366866/57909132-7db57080-78b4-11e9-9429-1ed2f430b975.png)

**Comment by deniro21** [comment] 2019-05-22 10:36
Same problem. The above arguments helped, but when you request some sites, you still get the error "Fatal error: in ...xxx...Exception.php on line 55 puphpeeter". For example, the Google site opens without errors, but the Yandex site(https://yandex.ru) with this error. In the classic version of the puppeteer I do not observe such an error.

**Comment by deniro21** [comment] 2019-05-22 11:26
I think the problem is in timeout. After increasing the timeout, the problem was resolved.
`require_once "vendor/autoload.php";

use Nesk\Puphpeteer\Puppeteer;

$puppeteer = new Puppeteer([
    'read_timeout' => 95, // In seconds
]);


$browser = $puppeteer->launch([
    'args' => [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
        '--incognito',
    ]
]);

$page = $browser->newPage();
$page->goto('https://yandex.ru',[
    'timeout' => 90000, // In milliseconds
]);
$page->screenshot(['path' => 'example.png']);

$browser->close();`

**Comment by deniro21** [comment] 2019-05-22 11:31
I conducted tests. If you radically reduce the timeout, for example, to 5 seconds, then the fatal error will appear almost constantly, regardless of the site. This is a bug, because if I parse a lot of sites in a loop, the inaccessibility of one site will turn off the entire script.

**Comment by damonbakker** [comment] 2020-03-25 07:43
Disabling sandbox is the only way to make it work on windows 10 for me currently!
Thanks for that.

It might be good to configure a sandbox manually but most documentation only explains how to do that for linux systems. Make sure you can trust the content of the pages you visit since you don't have any sandbox protection.
