### ISSUE TITLE
Cannot read property 'port' of null

### ISSUE THREAD

**Issue by 7starsone** [nesk/puphpeteer#7] opened 2018-06-12 16:48 UTC
Hello,
sometimes I had this error on php log

`Cannot read property 'port' of null`

and today many times in a row, so the php script doesn't run at all and the complete error is

```
[12-Jun-2018 18:44:03 Europe/Berlin] PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'node' '/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/serve.js' '/home/myuser/public_html/tmp/pjs/vendor/nesk/puphpeteer/src/PuppeteerConnectionDelegate.js' '{"idle_timeout":60}'" failed.

Exit Code: 1(General error)

Working directory: /home/myuser/public_html/tmp/pjs

Output:
================


Error Output:
================
/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:49
        process.stdout.write(`${this.server.address().port}\n`);
                                                     ^

TypeError: Cannot read property 'port' of null
    at Server.writePortToOutput (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:49:54)
    at Object.<anonymous> (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/serve.js:18:8)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/ in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php on line 232
```

Is there a fix about it? Thanks

**Comment by 7starsone** [comment] 2018-06-12 17:20
and also

```
[12-Jun-2018 19:18:45 Europe/Berlin] PHP Fatal error:  Uncaught Nesk\Rialto\Exceptions\Node\FatalException: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php:230
Stack trace:
#0 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php(290): Nesk\Rialto\ProcessSupervisor->checkProcessStatus()
#1 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(83): Nesk\Rialto\ProcessSupervisor->executeInstruction('{"type":"call",...')
#2 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(91): Nesk\Rialto\Data\BasicResource->proxyAction('call', 'content', Array)
#3 /home/myuser/public_html/tmp/pjs/icecatscrapeMULTI.php(195): Nesk\Rialto\Data\BasicResource->__call('content', Array)
#4 {main}
  thrown in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php on line 230
```

**Comment by 7starsone** [comment] 2018-06-12 17:29
so, the problems are about stability. Sometimes it doesn't run at all (the 1st case), sometimes randomly stops (2nd case) and sometimes is working for 1 hour, 2 hours...but most of the time is unstable

**Comment by 7starsone** [comment] 2018-06-12 17:36
another

```
[12-Jun-2018 19:35:01 Europe/Berlin] PHP Fatal error:  Uncaught Nesk\Rialto\Exceptions\Node\FatalException: Unexpected token { in JSON at position 145 in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php:230
Stack trace:
#0 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php(290): Nesk\Rialto\ProcessSupervisor->checkProcessStatus()
#1 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(83): Nesk\Rialto\ProcessSupervisor->executeInstruction('{"type":"call",...')
#2 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(91): Nesk\Rialto\Data\BasicResource->proxyAction('call', 'goto', Array)
#3 /home/myuser/public_html/tmp/pjs/myscript.php(178): Nesk\Rialto\Data\BasicResource->__call('goto', Array)
#4 {main}
  thrown in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php on line 230
```

**Comment by 7starsone** [comment] 2018-06-18 12:09
any news about this, please? Eg. how to change port and what's the cause of the other issues? thanks

**Comment by nesk** [comment] 2018-06-18 15:19
This should be fixed, please run `composer update nesk/rialto` to update PuPHPeteer's dependencies. The third issue should be fixed too.

About the second issue, [this is a Puppeteer issue](https://github.com/GoogleChrome/puppeteer/issues/1325), it has nothing to do with my project.

**Closed by nesk** 2018-06-18 15:19 UTC

**Comment by 7starsone** [comment] 2018-06-18 17:54
Thank you. About the 2nd, this should be the fix...
https://github.com/GoogleChrome/puppeteer/commit/ddfdaf97c5b3375dde5fab4f4ac01f10eaa5583f

at the moment, the script doesn't exit anymore, anyway if any update I'll let you know...

**Comment by 7starsone** [comment] 2018-06-18 18:53
This
```
[18-Jun-2018 20:01:47 Europe/Berlin] PHP Fatal error:  Uncaught Nesk\Rialto\Exceptions\Node\FatalException: listen EADDRINUSE :: in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php:230
Stack trace:
#0 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php(257): Nesk\Rialto\ProcessSupervisor->checkProcessStatus()
#1 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php(113): Nesk\Rialto\ProcessSupervisor->serverPort()
#2 /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/AbstractEntryPoint.php(30): Nesk\Rialto\ProcessSupervisor->__construct('/home/myuser/pu...', Object(Nesk\Puphpeteer\PuppeteerProcessDelegate), Array)
#3 /home/myuser/public_html/tmp/pjs/vendor/nesk/puphpeteer/src/Puppeteer.php(25): Nesk\Rialto\AbstractEntryPoint->__construct('/home/myuser/pu...', Object(Nesk\Puphpeteer\PuppeteerProcessDelegate), Array, Array)
#4 /home/myuser/public_html/tmp/pjs/myscript.php(171): Nesk\Puphpeteer\Puppeteer->__construct()
#5 {main}
  thrown in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php on line 230
```

**Comment by nesk** [comment] 2018-06-18 19:00
Give me reproducible examples with their logs. There is [an issue template for this](https://github.com/nesk/puphpeteer/issues/new?template=bug_report.md), use it.

**Comment by 7starsone** [comment] 2018-06-19 10:59
I would prefer to continue here, please.
This is a log at pastebin for "_Cannot find context with specified id undefined_"
https://pastebin.com/eL131jeB

despite I edited the **.../node_modules/puppeteer/lib/FrameManager.js** as suggested on that commit

then, I'm trying to get another **listen EADDRINUSE** on log, also often detectable, but the the most frequent and annoying is this

**Comment by 7starsone** [comment] 2018-06-19 11:09
This for **listen EADDRINUSE**

```
[2018-06-19 13:00:43] PuPHPeteer.DEBUG: Starting process... [] []
[2018-06-19 13:00:43] PuPHPeteer.DEBUG: [PID 20853] Process started [] []
[2018-06-19 13:00:43] PuPHPeteer.ERROR: [PID 20853] [stderr] {"__rialto_error__":true,"message":"listen EADDRINUSE ::","stack":"Error: listen EADDRINUSE ::\n    at Server.setupListenHandle [as _listen2] (net.js:1346:14)\n    at listenInCluster (net.js:1387:12)\n    at Server.listen (net.js:1475:7)\n    at resolve (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:43:25)\n    at new Promise (<anonymous>)\n    at Server.start (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:42:16)\n    at new Server (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:21:29)\n    at Object.<anonymous> (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/serve.js:15:16)\n    at Module._compile (internal/modules/cjs/loader.js:654:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)"} [] []
```

**Comment by nesk** [comment] 2018-06-19 12:11
We can continue here if you want, but I need you to provide all the data I ask for in the issue template, otherwise I will not be able to help you. You're providing me logs but everything else is missing, so create a new post in this issue but with [this template](https://github.com/nesk/puphpeteer/issues/new?template=bug_report.md), just copy/paste it and fill the missing parts.

I need code examples to reproduce the error (and remove from the code/logs the parts I'm not interested in).

Thank you.

**Comment by 7starsone** [comment] 2018-06-19 12:13
So, whenever **listen EADDRINUSE** is the error, this is the log and there are no other rows related to URLs, page content and so on...

```
[2018-06-19 14:06:02] PuPHPeteer.DEBUG: [options] {"read_timeout":35,"logger":{}} [] []
[2018-06-19 14:06:02] PuPHPeteer.DEBUG: Starting process... [] []
[2018-06-19 14:06:02] PuPHPeteer.DEBUG: [PID 5217] Process started [] []
[2018-06-19 14:06:02] PuPHPeteer.ERROR: [PID 5217] [stderr] {"__rialto_error__":true,"message":"listen EADDRINUSE ::","stack":"Error: listen EADDRINUSE ::\n    at Server.setupListenHandle [as _listen2] (net.js:1346:14)\n    at listenInCluster (net.js:1387:12)\n    at Server.listen (net.js:1475:7)\n    at resolve (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:43:25)\n    at new Promise (<anonymous>)\n    at Server.start (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:42:16)\n    at new Server (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/Server.js:21:29)\n    at Object.<anonymous> (/home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/node-process/serve.js:15:16)\n    at Module._compile (internal/modules/cjs/loader.js:654:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)"} [] []
```

**Comment by 7starsone** [comment] 2018-06-19 12:20
a code example

```
require 'vendor/autoload.php';
use Nesk\Puphpeteer\Puppeteer;
use Nesk\Rialto\Exceptions\Node;
...
...
$logPath = '/home/myuser/public_html/tmp/pupe.log';
$logger = new \Monolog\Logger('PuPHPeteer');
$logger->pushHandler(new \Monolog\Handler\StreamHandler($logPath, \Monolog\Logger::DEBUG));
$puppeteer = new Puppeteer(['logger' => $logger]);

$browser = $puppeteer->launch([
    'args' => ['--no-sandbox', '--disable-setuid-sandbox', '--proxy-server=xx.xxx.xx.xx:3128'],
]);
$page = $browser->newPage();
$page->setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36');
$url = "https://myurl.";
$country = array("it", "de", "fr", "pt", "es", "co.uk");

foreach ($country as $p) {
$x = 0;
$target_url = "$url$p/search?keyword=$ean";
echo "url is $target_url \n";

try {
    $page->tryCatch->goto($target_url, [
    'waitUntil' => 'networkidle0', 
]);
} catch (Node\Exception $exception) {
    // Handle the exception...
	$browser->close();
	continue 2;
}
....
....
```

**Comment by 7starsone** [comment] 2018-06-19 13:41
maybe, could it be useful to do
`exec ("killall -9 node");` 

at the begin of the php script
and then sleep some seconds and start to run the rest as usual?
Thanks

**Comment by 7starsone** [comment] 2018-06-19 13:59
I'm trying with something like

```
while ($i != 1) {
	$output = shell_exec('ps -C node -f');
	if (strpos($output, "node /home/myuser/public_html/tmp/pjs/")!==false) { 
	  exec('killall node');
	  sleep(5);
	  }
	$output = shell_exec('ps -C node -f');  
	 if (strpos($output, "node /home/myuser/public_html/tmp/pjs/")===false) { 
	  $i = 1;
	  } 
}
```
I'll let you know about the result, if it returns **listen EADDRINUSE** again or not, even if it would be better to solve it from scratch

**Comment by 7starsone** [comment] 2018-06-19 15:10
well, no, I can confirm that node processes are not running but **listen EADDRINUSE** may be a frequent error, not related to the running node process and after 10 minutes the script doesn't run because of that, even if launched one time a minute

**Comment by nesk** [comment] 2018-06-20 14:23
I strongly believe all of this is due to your environment, sorry but I don't know how to solve your issue here…

Just in case, I will try to run PuPHPeteer on CentOS 7.5 in the next days, but I'm clearly certain I will not encounter the same issues as you.

**Comment by 7starsone** [comment] 2018-06-20 14:44
pardon, how could you be "clearly certain" if you didn't try yet? I tried to edit the FrameManager.js as suggested but I often still get **Cannot find context with specified id undefined**. I asked about this on puppeteer but waiting for a reply. 
Then, the only fixed issue at the moment is `Cannot read property 'port' of null`, no more detected and still many times `listen EADDRINUSE`.
This is the situation here now, my software versions are as above, CentOS 7.5.1804 and...that's it.

Thank you

**Comment by nesk** [comment] 2018-06-20 15:08
I told you this was very probably an issue [with Puppeteer](https://github.com/GoogleChrome/puppeteer/issues/1325), not with my project. I bet you have not even tried to crawl your website with Puppeteer (in JS) instead of PuPHPeteer (in PHP). If you want to prove me the issue comes from my project, either you show me it doesn't happen in Puppeteer with nearly the same code, either you provide me a reproducible example with PuPHPeteer. You did none of them.

I also told you to use my template issue which provides many more informations than the ones you're providing me.

It seems like you're spamming this issue in hope I will solve **your** issues and not PuPHPeteer's ones, you're not making any search by yourself.

Clearly, I'm not in good terms with you, so I will just lock this issue. Feel free to create a new one if you want, but use the template and do some research on your own before.

I encourage you to watch [this video](https://www.youtube.com/watch?v=53zkBvL4ZB4) to learn how to properly report bugs in the future.

>pardon, how could you be "clearly certain" if you didn't try yet?

Based on experience. I can be wrong, but I'm mostly certain about that because I know the inners of my library.
