### ISSUE TITLE
Exit Code: -2147483645(Unknown error)

### ISSUE THREAD

**Issue by camilamilagros** [nesk/puphpeteer#47] opened 2019-03-21 20:45 UTC
**Describe the bug**
I tried to use PuPHPeteer but I had trouble with the node command, so I send the execution path of node to the constructor and now a have an "Unknown Error". It is triggered while trying to execute this command:
```
"C:\Program Files\nodejs\node" "C:\laragon\www\scrapers-refactoring\vendor\nesk\puphpeteer\src/get-puppeteer-version.js"
```

I tried this in a terminal and it works fine and returns "1.13.0". 

**Reproducible example**
```php
use Nesk\Puphpeteer\Puppeteer;
$logger = new \Monolog\Logger('PuPHPeteer');
$logger->pushHandler(new \Monolog\Handler\StreamHandler('puPHPeteer.log', \Monolog\Logger::DEBUG));

$puppeteer = new Puppeteer(
      [
         'executable_path' => 'C:\Program Files\nodejs\node',
         'logger' => $logger,
         'log_node_console' => true,
         'log_browser_console' => true,
         'debug' => true,
     ]
);
```

**Expected behavior**
Create a Puppeteer instance.

**Generated logs**
There were no logs generated, probably because the issue is in the constructor

**Screenshots**
![image](https://user-images.githubusercontent.com/22065066/54783667-f919df00-4bef-11e9-97cc-cb1b944f70a6.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Node version: 10.15.1
 - PHP version 7.2.11

My Node package manager is:
 - [x] NPM (6.4.1)
 - [ ] Yarn (specify the version)
 - [ ] Other (specify the name and version)

**Additional context**
I'm using Laragon, so I don't know if it's a configuration thing, any help would be nice :)

**Comment by nesk** [comment] 2019-03-24 17:03
I've downloaded the Windows 10 virtual machine provided by Microsoft [on their website](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and then installed Laragon. I was able to run all of the README examples without any issue. 

Note that I was using Laragon's terminal and I didn't change the executable path of Node. I was using the Node executable provided by Laragon. It seems like you have two installations of Node, maybe that's the issue.

I'm closing this issue, but if you still encounter this, provide me a reproducible example (it can be a VMware VM) so I can test myself and I will reopen the issue.

**Closed by nesk** 2019-03-24 17:03 UTC

**Comment by raymondtri** [comment] 2019-07-06 20:00
This issue crops up when you try to run this using laravel's php artisan serve outside of a development environment such as Laragon.

When using command prompt or powershell, the real issue that is popping up is this:
```
socket: (10106) The requested service provider could not be loaded or initialized.
```

I believe that this socket issue is a windows security thing, as some googling shows it has popped up in several other projects around the internet:
https://travis-ci.community/t/socket-the-requested-service-provider-could-not-be-loaded-or-initialized/1127
https://github.com/aerokube/selenoid/issues/657

I think the problem is with how the process is being created, but it looks like you all are just using Symfony processes in https://github.com/nesk/rialto/blob/dev/src/ProcessSupervisor.php#L251. Could be deeper than just this package.

**Comment by raymondtri** [comment] 2019-07-06 22:08
Some deeper digging, looks like a permissions issue with how Symfony is trying to start node.js

https://www.pcreview.co.uk/threads/asp-net-state-service-wont-start.3422497/

**Comment by nesk** [comment] 2019-07-08 11:01
Did you try to run with admin rights? Did it work?

**Comment by raymondtri** [comment] 2019-07-08 12:46
I run php artisan serve via powershell and even with admin rights it did not work. I think it is due to the fact that (admin) powershell is running the artisan webserver, but when php is being executed it is not being executed with elevated permissions. Therefore when it tries to run node, it cannot create a socket.

That may not be entirely accurate, but that's the direction my tests thus far have pointed me in. I'm not enough of a windows expert to give a definitive answer. My next move is going to be trying to ensure that php runs as an admin at all times and then test it that way.

I tried running netsh winsock reset and all of that to no avail.

**Comment by raymondtri** [comment] 2019-07-08 20:19
Alright so it does appear to be a permissions thing. If I run the raw command
`
node C:\Users\xxx\xxxxx\vendor\nesk\rialto\src/node-process/serve.js C:\Users\xxx\xxxxx\vendor\nesk\puphpeteer\src\PuppeteerConnectionDelegate.js '{"idle_timeout":60,"log_node_console":false,"log_browser_console":false}'
`

It will actually request permissions to run node.js as an administrator. I'm thinking that the permissions dialog does not open up when it is run in the background with php.

**Comment by raymondtri** [comment] 2019-07-08 21:29
So, it is definitely a permissions issue and the issue comes with running php artisan serve which apparently does not like running with elevated permissions on windows.

The recommendation (which worked for me) is to use instead, Laravel Valet. 

https://github.com/cretueusebiu/valet-windows/
