### ISSUE TITLE
$page->addScriptTag does not work

### ISSUE THREAD

**Issue by cyberbeat** [nesk/puphpeteer#52] opened 2019-07-03 08:12 UTC
addScriptTag does not work, see example:

**Reproducible example**
```php

$this->page->goto($url);
$res = $this->page->addScriptTag([
	"path" => "my_script_in_current_working_dir.js"
]);
$result = $this->page->evaluate(JsFunction::createWithBody("function_from_script_call();"));

```

**Expected behavior**
The function should be executed

**Generated logs**
```
Fatal error: Uncaught Nesk\Rialto\Exceptions\Node\FatalException: Evaluation failed: ReferenceError: function_from_script_call is not defined
```

**Environment (please complete the following information):**
 - OS: Opensuse Tumbleweed
 - Node version: 8.15.1
 - PHP version 7.3.6

My Node package manager is:
 - [x] NPM (specify the version)
 - [ ] Yarn (specify the version)
 - [ ] Other (specify the name and version)

**Comment by nesk** [comment] 2019-07-04 07:58
Just tried with this simple code and it works, I can't reproduce your bug:

```php
<?php

require 'vendor/autoload.php';

use Nesk\Puphpeteer\Puppeteer;
use Nesk\Rialto\Data\JsFunction;

$puppeteer = new Puppeteer;
$browser = $puppeteer->launch();
$page = $browser->newPage();
$page->goto('https://example.com');

$helloFunc = 'const hello = () => "Hello World!"';
$page->addScriptTag(['content' => $helloFunc]);

$result = $page->evaluate(JsFunction::createWithBody('return hello()'));

var_dump($result); // Prints: string(12) "Hello World!"
```

Maybe the path to your file `my_script_in_current_working_dir.js` is not correct? Try to pass an absolute path to avoid common mistakes with relative ones.

Since this is not a bug with PuPHPeteer, I'm closing this issue, but feel free to provide me an answer with more details and a reproducible example.

**Closed by nesk** 2019-07-04 07:58 UTC
